apiVersion: v1
kind: ConfigMap
metadata:
  name: home-assistant-config-seed
  namespace: home-assistant
  labels:
    app: home-assistant
data:
  configuration.yaml: |
    default_config:

    cloud:

