  # Install Cilium
- name: Install Cilium CLI
  shell: |
    curl -L --remote-name-all https://github.com/cilium/cilium-cli/releases/latest/download/cilium-linux-amd64.tar.gz{,.sha256sum}
    sha256sum --check cilium-linux-amd64.tar.gz.sha256sum
    tar xzvf cilium-linux-amd64.tar.gz
    chmod +x cilium
    mkdir -p /home/k8s/.local/bin
    mv cilium /home/k8s/.local/bin/
  args:
    creates: /home/k8s/.local/bin/cilium

- name: Check if Cilium is installed
  shell: |
    /home/k8s/.local/bin/cilium status
  register: cilium_status
  failed_when: false
  changed_when: false

- name: Deploy or Update Cilium
  shell: |
    /home/k8s/.local/bin/cilium install --restart-unmanaged
    /home/k8s/.local/bin/cilium status --wait
  when: cilium_status.rc != 0 or cilium_status.stdout is search("needs update")
  environment:
    KUBECONFIG: /home/k8s/.kube/config