---
- name: Install dependencies
  apt:
    name:
      - curl
      - apt-transport-https
      - ca-certificates
      - software-properties-common
      - python3-pip
      - python3-requests
      - python3-kubernetes
    state: latest
    update_cache: yes

# Install kubectl
- name: Download the latest kubectl binary
  shell: |
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    chmod +x kubectl
    mv kubectl /usr/bin/kubectl

- name: Verify kubectl installation
  command: kubectl version --client

# Install Helm
- name: Install Helm
  shell: |
    curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | HELM_INSTALL_DIR=/usr/bin/ bash -s

# Create a user for Kubernetes
- name: Create kubernetes user
  user:
    name: "k8s"
    state: present
    shell: /bin/bash

- name: Check if k3s is already installed
  stat:
    path: /usr/local/bin/k3s
  register: k3s_installed

- name: Install k3s
  shell: |
    curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC='' sh - \   
    --flannel-backend=none --disable-kube-proxy --disable-network-policy \
    --disable servicelb --disable traefik --cluster-init
  args:
    executable: /bin/bash
  when: not k3s_installed.stat.exists

- name: Wait for k3s to be ready
  shell: |
    k3s kubectl get nodes
  retries: 30
  delay: 10
  until: result is succeeded
  register: result

- name: Create .kube directory for k8s user
  file:
    path: /home/k8s/.kube
    state: directory
    owner: k8s
    group: k8s
    mode: '0755'

- name: Copy k3s kubeconfig to k8s user home
  shell: |
    cp /etc/rancher/k3s/k3s.yaml /home/k8s/.kube/config
    chown k8s:k8s /home/k8s/.kube/config
    chmod 600 /home/k8s/.kube/config
  args:
    executable: /bin/bash

# Post-installation tasks

## Install Cilium CNI
- import_tasks: cni.yml
  become: yes
  become_user: k8s
  become_method: sudo 
  become_flags: "-i"

## Install Cert-manager
- import_tasks: app-base/cert-manager.yml
  become: yes
  become_user: k8s
  become_method: sudo 
  become_flags: "-i"

## Install Vault
- import_tasks: app-base/vault.yml
  become: yes
  become_user: k8s
  become_method: sudo 
  become_flags: "-i"

## Install Vault
- import_tasks: app-base/cd.yml
  become: yes
  become_user: k8s
  become_method: sudo 
  become_flags: "-i"