---
- name: Install dependencies
  apt:
    name:
      - curl
      - apt-transport-https
      - ca-certificates
      - software-properties-common
    state: latest
    update_cache: yes

# Install kubectl
- name: Download the latest kubectl binary
  shell: |
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    chmod +x kubectl
    mv kubectl /usr/bin/kubectl
  args:
    creates: kubectl

- name: Verify kubectl installation
  command: kubectl version --client

# Install Helm
- name: Install Helm
  shell: |
    curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | HELM_INSTALL_DIR=/usr/bin/ bash -s
  args:
    creates: /usr/bin/helm

# Create a user for Kubernetes
- name: Create kubernetes user
  user:
    name: "k8s"
    state: present
    shell: /bin/bash
    append: yes

- name: Install MicroK8s
  snap:
    name: microk8s
    classic: yes
    state: enabled

- name: Add user to microk8s group
  user:
    name: k8s
    groups: microk8s
    append: yes

- import_tasks: microk8s-install.yml
  become: yes
  become_user: k8s
  become_method: sudo 
  become_flags: "-i"

# Post-installation tasks
#- import_tasks: cni.yml
#  become: yes
#  become_user: k8s
#  become_method: sudo 
#  become_flags: "-i"