---
microk8s_addons:
  - community
  - cis-hardening
  - kubearmor
  - dns
  - openebs
  - ingress
  - cert-manager
  - prometheus
  - helm3
  - istio
  - metrics-server
#  - registry
#  - cilium
#  - metallb