- name: Ensure unattended-upgrades is installed
  apt:
    name: unattended-upgrades
    state: latest
    update_cache: yes

- name: Configure unattended-upgrades
  copy:
    src: files/unattended-upgrades.conf
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: '0644'

- name: Enable unattended-upgrades
  command: dpkg-reconfigure -f noninteractive unattended-upgrades

- name: Ensure unattended-upgrades service is running
  service:
    name: unattended-upgrades
    state: started
    enabled: yes

# Install snapd 
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install snapd
  apt:
    name: snapd
    state: present

- name: Ensure snapd is running
  service:
    name: snapd
    state: started
    enabled: yes

# Install fail2ban
- name: Install fail2ban
  apt:
    name: fail2ban
    state: present

## Backup original configuration files
- name: Check if /etc/fail2ban/jail.local exists
  stat:
    path: /etc/fail2ban/jail.local
  register: jail_local_stat

- name: Backup original jail.local if it exists and no backup yet
  copy:
    src: /etc/fail2ban/jail.local
    dest: /etc/fail2ban/jail.local.orig
    remote_src: yes
    owner: root
    group: root
    mode: '0644'
  when:
    - jail_local_stat.stat.exists
    - not jail_local_stat.stat.islnk
    - not (jail_local_stat.stat.path + ".orig") | path_exists

## Start and enable fail2ban service
- name: Ensure fail2ban service is running
  service:
    name: fail2ban
    state: started
    enabled: yes

- name: Deploy fail2ban jail.local configuration
  copy:
    src: jail.local
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: '0644'
  notify: Restart fail2ban
