- name: Ensure unattended-upgrades is installed
  apt:
    name: unattended-upgrades
    state: latest
    update_cache: yes

- name: Configure unattended-upgrades
  copy:
    src: files/unattended-upgrades.conf
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: '0644'

- name: Enable unattended-upgrades
  command: dpkg-reconfigure -f noninteractive unattended-upgrades

- name: Ensure unattended-upgrades service is running
  service:
    name: unattended-upgrades
    state: started
    enabled: yes

# Install snapd 
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install snapd
  apt:
    name: snapd
    state: present

- name: Ensure snapd is running
  service:
    name: snapd
    state: started
    enabled: yes

# Install fail2ban
- name: Install fail2ban
  apt:
    name: fail2ban
    state: present

## Backup original configuration files
- name: Check if /etc/fail2ban/jail.local exists
  stat:
    path: /etc/fail2ban/jail.local
  register: jail_local_stat

- name: Check if /etc/fail2ban/jail.local.orig exists
  stat:
    path: /etc/fail2ban/jail.local.orig
  register: jail_local_orig_stat

- name: Backup original jail.local if it exists and no backup yet
  copy:
    src: /etc/fail2ban/jail.local
    dest: /etc/fail2ban/jail.local.orig
    remote_src: yes
    owner: root
    group: root
    mode: '0644'
  when:
    - jail_local_stat.stat.exists
    - not jail_local_stat.stat.islnk
    - not jail_local_orig_stat.stat.exists

## Start and enable fail2ban service
- name: Ensure fail2ban service is running
  service:
    name: fail2ban
    state: started
    enabled: yes

- name: Deploy fail2ban jail.local configuration
  copy:
    src: jail.local
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: '0644'
  notify: Restart fail2ban

## Update dynu ip
- name: Update Dynu DDNS with current public IP
  vars:
    dynu_api_key: "{{ lookup('env', 'DYNU_API_KEY') }}"
    dynu_hostname: "kamos.freeddns.org"
  block:
    - name: Get current public IP
      uri:
        url: https://api.ipify.org
        return_content: yes
      register: public_ip

    - name: Update Dynu DDNS record using curl and API
      ansible.builtin.uri:
        url: "https://api.dynu.com/v2/dns"
        method: GET
        headers:
          accept: "application/json"
          API-Key: "{{ dynu_api_key }}"
        return_content: yes
      register: dynu_dns_list

    - name: Find DNS record ID for hostname
      set_fact:
        dynu_dns_id: "{{ item.id }}"
      loop: "{{ (dynu_dns_list.json | default([])).domains | default([]) }}"
      when: item.name == dynu_hostname
      register: dynu_dns_id_result

    - name: Update Dynu DDNS record with current public IP
      ansible.builtin.uri:
        url: "https://api.dynu.com/v2/dns/{{ dynu_dns_id_result.results[0].ansible_facts.dynu_dns_id }}/record"
        method: GET
        headers:
          accept: "application/json"
          API-Key: "{{ dynu_api_key }}"
        return_content: yes
      register: dynu_dns_records

    # Debug
    - name: Find A record ID for hostname
      set_fact:
        dynu_list: "{{ (dynu_dns_records.json | default([])).dnsRecords | default([]) }}"
    
    - name: Debug Dynu DNS records
      debug:
        var: dynu_list

    - name: Update IP record with current public IP
      ansible.builtin.uri:
        url: "https://api.dynu.com/v2/dns/{{ dynu_dns_id_result.results[0].ansible_facts.dynu_dns_id }}"
        method: POST
        headers:
          accept: "application/json"
          API-Key: "{{ dynu_api_key }}"
          Content-Type: "application/json"
        body_format: json
        body:
          name: "{{ dynu_hostname }}"
          ipv4Address: "{{ public_ip.content }}"
      register: dynu_update_result
      
    - name: Show Dynu DDNS update result
      debug:
        var: dynu_update_result.stdout