apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-kubernetes
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Yayg/kamos-ansible.git'
    targetRevision: HEAD
    path: argocd/hello-kubernetes
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
