- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_facts['lsb']['codename'] }} stable"
    state: present
    
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Docker
  apt:
    name: docker-ce
    state: latest

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes

- name: Ensure Docker is running
  command: docker info
  register: docker_info
  changed_when: false
  
- name: Verify Docker installation
  assert:
    that:
      - docker_info.stdout is search("Server Version")
    fail_msg: "Docker installation failed."

- name: Ensure Docker group is present
  group:
    name: docker
    state: present

- name: Add user to Docker group
  user:
    name: "{{ ansible_user }}"
    group: docker
    append: yes
