- name: Install kind dependencies
  apt:
    name:
      - curl
      - apt-transport-https
      - ca-certificates
      - software-properties-common
    state: latest
    update_cache: yes

- include_tasks: docker.yml

- name: Create kind user
  user:
    name: "kind"
    state: present
    shell: /bin/bash
    groups: docker
    append: yes

- import_tasks: kind.yml
  become: yes
  become_user: kind