---
- name: Update Dynu DDNS with current public IP
  vars:
    dynu_api_key: "{{ lookup('env', 'DYNU_API_KEY') }}"
    dynu_hostname: "kamos.freeddns.org"
  block:
    - name: Get current public IP
      uri:
        url: https://api.ipify.org
        return_content: yes
      register: public_ip

    - name: Update Dynu DDNS record using curl and API
      ansible.builtin.uri:
        url: "https://api.dynu.com/v2/dns"
        method: GET
        headers:
          accept: "application/json"
          API-Key: "{{ dynu_api_key }}"
        return_content: yes
      register: dynu_dns_list

    - name: Find DNS record ID for hostname
      set_fact:
        dynu_dns_id: "{{ item.id }}"
      loop: "{{ (dynu_dns_list.json | default([])).domains | default([]) }}"
      when: item.name == dynu_hostname
      register: dynu_dns_id_result

    - name: Update Dynu DDNS record with current public IP
      ansible.builtin.uri:
        url: "https://api.dynu.com/v2/dns/{{ dynu_dns_id_result.results[0].ansible_facts.dynu_dns_id }}/record"
        method: GET
        headers:
          accept: "application/json"
          API-Key: "{{ dynu_api_key }}"
        return_content: yes
      register: dynu_dns_records

    # Debug
    - name: Find A record ID for hostname
      set_fact:
        dynu_list: "{{ (dynu_dns_records.json | default([])).dnsRecords | default([]) }}"
    
    - name: Debug Dynu DNS records
      debug:
        var: dynu_list

    - name: Find A record ID for hostname
      set_fact:
        dynu_a_record_id: "{{ item.id }}"
      loop: "{{ (dynu_dns_records.json | default([])).dnsRecords | default([]) }}"
      when: item.type == 'A' and item.hostname == dynu_hostname
      register: dynu_a_record_id_result

    - name: Update A record with current public IP
      ansible.builtin.uri:
        url: "https://api.dynu.com/v2/dns/{{ dynu_dns_id_result.results[0].ansible_facts.dynu_dns_id }}/record/{{ dynu_a_record_id_result.results[0].ansible_facts.dynu_a_record_id }}"
        method: POST
        headers:
          accept: "application/json"
          API-Key: "{{ dynu_api_key }}"
          Content-Type: "application/json"
        body_format: json
        body:
          hostname: "{{ dynu_hostname }}"
          nodeName: ""
          recordType: "A"
          content: "{{ public_ip.content }}"
          ttl: 120
      register: dynu_update_result
      
    - name: Show Dynu DDNS update result
      debug:
        var: dynu_update_result.stdout

- name: Create ClusterIssuer for Let's Encrypt (Staging)
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: cert-manager.io/v1
      kind: ClusterIssuer
      metadata:
        name: letsencrypt-staging
      spec:
        acme:
          server: https://acme-staging-v02.api.letsencrypt.org/directory
          email: me@raf.sh
          privateKeySecretRef:
            name: letsencrypt-staging
          solvers:
            - http01:
                ingress:
                  class: nginx

- name: Create ClusterIssuer for Let's Encrypt (Production)
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: cert-manager.io/v1
      kind: ClusterIssuer
      metadata:
        name: letsencrypt-prod
      spec:
        acme:
          server: https://acme-v02.api.letsencrypt.org/directory
          email: me@raf.sh
          privateKeySecretRef:
            name: letsencrypt-prod
          solvers:
            - http01:
                ingress:
                  class: nginx