---
# Install HashiCorp Vault in Kubernetes
- name: Add the HashiCorp Helm repository
  shell: |
    helm repo add hashicorp https://helm.releases.hashicorp.com
    helm repo update
  environment:
    KUBECONFIG: /home/k8s/.kube/config

- name: Get latest Vault chart version
  shell: |
    helm search repo hashicorp/vault --devel -o json | jq -r '.[0].app_version'
  register: vault_app_version_result
  changed_when: false
  environment:
    KUBECONFIG: /home/k8s/.kube/config

- name: Set latest Vault chart version fact
  set_fact:
    vault_app_version: "{{ vault_app_version_result.stdout }}"

- name: Check if Vault Helm release exists
  community.kubernetes.helm_info:
    release_name: vault
    release_namespace: vault
    kubeconfig: /home/k8s/.kube/config
  register: vault_helm_info
  ignore_errors: yes

- name: Deploy or upgrade Vault with Helm
  community.kubernetes.helm:
    name: vault
    chart_ref: hashicorp/vault
    namespace: vault
    create_namespace: yes
    state: present
  register: vault_helm_deploy
#  when: vault_helm_info.status is not defined or
#        vault_helm_info.status.status == "FAILED" or
#        vault_helm_info.status.appversion != vault_app_version

- name: Wait for Vault to be ready
  shell: |
    sleep 15
#    kubectl wait --namespace vault \ 15
#      --for=condition=available sts \ 15
#      --timeout=600s vault
  environment:
    KUBECONFIG: /home/k8s/.kube/config

# Only initialize Vault if it hasn't been initialized before
- name: Check if Vault is initialized
  shell: |
    kubectl -n vault wait --for=jsonpath='{.status.phase}'=Running pod vault-0 2>&1 > /dev/null
    kubectl exec -n vault vault-0 -- vault status -format=json | jq -r .initialized
  register: vault_initialized
  failed_when: false
  changed_when: false
  environment:
    KUBECONFIG: /home/k8s/.kube/config

- name: Debug vault_initialized value
  debug:
    var: vault_initialized

- name: Initialize Vault (only if not initialized)
  shell: |
    kubectl exec -n vault vault-0 -- vault operator init -key-shares=1 -key-threshold=1 -format=json > ~/.vault-init.json
    VAULT_ROOT_TOKEN=$(jq -r ".root_token" ~/.vault-init.json)
    kubectl create secret generic vault-root-token \
      --from-literal=token=$VAULT_ROOT_TOKEN \
      --namespace vault --dry-run=client -o yaml | kubectl apply -f -
  when: vault_initialized.stdout is defined and vault_initialized.stdout == "false"
  environment:
    KUBECONFIG: /home/k8s/.kube/config

# Unseal Vault if a new version was deployed or upgraded
- name: Unseal Vault (if upgraded or newly deployed)
  shell: |
    VAULT_UNSEAL_KEY=$(jq -r ".unseal_keys_b64[0]" ~/.vault-init.json)
    kubectl exec -n vault vault-0 -- vault operator unseal $VAULT_UNSEAL_KEY
  environment:
    KUBECONFIG: /home/k8s/.kube/config


- name: Create Ingress to expose Vault UI with TLS from cert-manager
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: vault-ui
        namespace: vault
        annotations:
          kubernetes.io/ingress.class: "nginx"
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
      spec:
        tls:
        - hosts:
          - vault.kamos.freeddns.org
          secretName: vault-tls
        rules:
        - host: vault.kamos.freeddns.org
          http:
            paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: vault
                  port:
                    number: 8200
  environment:
    KUBECONFIG: /home/k8s/.kube/config